version: 2
updates:
  - package-ecosystem: "pip"
    directory: "app/" # Location of package manifests
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily

  - package-ecosystem: "docker"
    directory: "/app"
    schedule:
      interval: daily

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: daily
